---
title: "Housing Presentation Visualizations"
format: html

code-fold: true
code-tools: true
---

# \[Optional\] Set up radian terminal

Run `radian` in `pwsh` termminal (after `conda` has been activated).

# Imports

```{r Imports}
#| code-fold: show
#| code-summary: "Show the code"

library(pacman)

p_load(httpgd, tidyverse, magrittr, fredr, usethis, tidylog)

```

# FRED Data Request

## FRED API Key

```{r FRED_API_Key}
#| code-fold: show
#| code-summary: "Show the code"

# set fred api key
# edit_r_environ()
fredr_set_key("deee9e25196e8adae1bb08246163f630")

```

```{r FRED_Request_Function}


```

## Construction Statistics

```{r Construction_Stats}
#| code-fold: show
#| code-summary: "Show the code"
#| 
# construction stats

construction_stats <- pmap_dfr(
  .l = list(
    series_id = c("HOUST", "COMPUTSA", "PERMIT"),
    frequency = rep("m", 3), 
    observation_start = rep(as.Date("2022-01-01"), 3),
    units = rep("pc1", 3)
    ),
  .f = ~ fredr(series_id = ..1, frequency = ..2, observation_start = ..3, units = ..4)
) %>%
mutate(series_id = 
    case_when(
        series_id == "HOUST" ~ "Housing starts", 
        series_id == "COMPUTSA" ~ "Housing completions",
        series_id == "PERMIT" ~ "Building permits issued"
 ))
```

## Input Prices

```{r Input_Prices}
#| code-fold: show
#| code-summary: "Show the code"

# input prices
# to-do: seasonally adjust all?
# to-do: variable fo number of variables
housing_input_prices <- pmap_dfr(
  .l = list(
    series_id = c("WPUIP2311001", "WPUIP2311102", "WPUSI012011", "WPU01", "WPU131", "WPS101", "WPS133301"),
    frequency = rep("m", 7), 
    observation_start = rep(as.Date("2022-01-01"), 7),
    units = rep("pc1", 7)
    ),
  .f = ~ fredr(series_id = ..1, frequency = ..2, observation_start = ..3, units = ..4)
) %>%
mutate(series_id = 
    case_when(
        series_id == "WPUIP2311001" ~ "Residential construction goods PPI", 
        series_id == "WPUIP2311102" ~ "Residential construction services PPI",
        series_id == "WPUSI012011" ~ "Construction materials PPI",
        series_id == "WPU01" ~ "Lumber and wood products PPI",
        series_id == "WPU131" ~ "Glass PPI",
        series_id == "WPS101" ~ "Iron and steel PPI",
        series_id == "WPS133301" ~ "Ready-mix concrete PPI"
    )
)
```

## Home Finances

```{r Home_Prices}
#| code-fold: show
#| code-summary: "Show the code"

home_prices <- pmap_dfr(
  .l = list(
    series_id = c("CSUSHPISA", "MSPUS"),
    frequency = c("m", "q"), 
    observation_start = c(as.Date("2022-01-01"), as.Date("2021-11-01")),
    units = rep("pc1", 2)
    ),
  .f = ~ fredr(series_id = ..1, frequency = ..2, observation_start = ..3, units = ..4)
) %>%
mutate(series_id = 
    case_when(
        series_id == "CSUSHPISA" ~ "S&P/Case-Shiller U.S. National Home Price Index",
        series_id == "MSPUS" ~ "Median sales price of houses sold"
    ),
    date = case_when(
        series_id == "S&P/Case-Shiller U.S. National Home Price Index" ~ date,
        series_id == "Median sales price of houses sold" ~ date %m+% months(2)
    )
)

avg30YrFixedMortgage <- fredr(
    series_id = "MORTGAGE30US",
    observation_start = as.Date("2022-01-01"),
    frequency = "m",
    aggregation_method = "avg",
    units = "lin"
) %>%
mutate(series_id = 
    case_when(
        series_id == "MORTGAGE30US" ~ "Average 30-year fixed-rate mortgage"
    )
)
```

## Housing Starts
```{r housing_starts}
housing_starts <- fredr(
    series_id = "HOUST",
    frequency = "m", 
    observation_start = as.Date("2021-01-01"),
    units = "lin"
) %>%
mutate(series_id = 
    case_when(
        series_id == "HOUST" ~ "New Privately-Owned Housing Units Started: Total Units"
    )
) %>%
select(date, value) %>%
rename_at("value", ~"All Starts")

```

## Single Starts
```{r single_housing_starts}
single_housing_starts <- fredr(
    series_id = "HOUST1F",
    frequency = "m", 
    observation_start = as.Date("2021-01-01"),
    units = "lin"
) %>%
mutate(series_id = 
    case_when(
        series_id == "HOUST1F" ~ "New Privately-Owned Housing Units Started: Single Units"
    )
) %>%
select(date, value) %>%
rename_at("value", ~"Single Starts")

```

## Multi-Unit Starts
```{r multi_housing_starts}
multi_housing_starts <- fredr(
    series_id = "HOUST5F",
    frequency = "m", 
    observation_start = as.Date("2021-01-01"),
    units = "lin"
) %>%
mutate(series_id = 
    case_when(
        series_id == "HOUST5F" ~ "New Privately-Owned Housing Units Started: Multiple Units"
    )
) %>%
select(date, value) %>%
rename_at("value", ~"Multi Starts")
 
```

## Combined Starts
```{r comb_starts}
comb_starts = merge(merge(housing_starts, single_housing_starts, by = "date"), multi_housing_starts, by = "date") 

long_comb = comb_starts %>% 
    pivot_longer(cols = c("Multi Starts", "Single Starts", "All Starts"))

```

## Graphics

```{r Graphics}
# houseStarts %>%
#     ggplot(
#         mapping = aes(x = date, y = value, color = series_id)) +
#     geom_line() +
#     labs(x = "Observation Date", y = "% Change from 1 Year Ago", color = "Series")

graph_formatting <- list(
    scale_color_brewer(palette = "Paired"),
    scale_y_continuous(labels = scales::percent_format(scale = 1)),

    # specify custom font
    theme_minimal(base_family = "Roboto Condensed", base_size = 12),

    # make modifications to the theme, adjusting fonts and formatting
    theme(
        panel.grid.minor = element_blank(),
        plot.title = element_text(face = "bold", size = rel(1.7)),
        plot.subtitle = element_text(
            face = "plain", 
            size = rel(1.3), color = "grey70"
        ),
        plot.caption = element_text(
            face = "italic", size = rel(0.7),
            color = "grey70", hjust = 0
        ),
        strip.text = element_text(face = "bold", size = rel(1.1), hjust = 0),
        axis.title = element_text(face = "bold"),
        axis.title.x = element_text(margin = margin(t = 10), hjust = 0),
        axis.title.y = element_text(margin = margin(r = 10), hjust = 1),
        # strip.background = element_rect(fill = "grey90", color = NA),
        # panel.border = element_rect(color = "grey90", fill = NA),
        panel.background = element_rect(fill="white"),
        plot.background = element_rect(fill="white", color = NA),
        legend.position = "bottom"
    )
)

construction_stats_graph <- construction_stats %>%
    ggplot(
        data = ., mapping = aes(x = date, 
                                y = value, 
                                color = series_id)) +
    geom_line(size = 1) +
    labs(
        title = "Construction Stats",
        subtitle = "Housing starts, housing completions, building permits issued by % change from 1 year ago",
        x = NULL,
        y = NULL,
        color = NULL,
        caption = "Source: Federal Reserve Economic Data") +
    graph_formatting

ggsave(
    filename = "construction_stats.png",
    plot = construction_stats_graph,
    device = "png"
)

housing_inputs_graph <- housing_input_prices %>%
    ggplot(
        data = ., mapping = aes(x = date, 
                                y = value, 
                                color = series_id)) +
    geom_line(size = 1) +
    labs(
        title = "Housing inputs PPIs",
        subtitle = "Residential construction goods PPI, residential construction services PPI, construction materials PPI, lumber and wood products PPI, glass PPI, iron and steel PPI, ready-mix concrete PPI",
        x = NULL,
        y = NULL,
        color = NULL,
        caption = "Source: Federal Reserve Economic Data") +
    graph_formatting

ggsave(
    filename = "housing_inputs.png",
    plot = housing_inputs_graph,
    device = "png"
)

home_prices_graph <- home_prices %>%
    ggplot(
        data = ., mapping = aes(x = date, 
                                y = value, 
                                color = series_id)) +
    geom_line(size = 1) +
    labs(
        title = "Home prices",
        subtitle = "S&P/Case-Shiller U.S. National Home Price Index, median sales price of houses sold",
        x = NULL,
        y = NULL,
        color = NULL,
        caption = "Source: Federal Reserve Economic Data") +
    graph_formatting

ggsave(
    filename = "home_prices.png",
    plot = home_prices_graph,
    device = "png"
)

mortgage_rate_graph <- avg30YrFixedMortgage %>%
    ggplot(
        data = ., mapping = aes(x = date, 
                                y = value, 
                                color = series_id)) +
    geom_line(size = 1) +
    labs(
        title = "Mortgage Rates",
        subtitle = "Average 30-year fixed-rate mortgage rates",
        x = NULL,
        y = NULL,
        color = NULL,
        caption = "Source: Federal Reserve Economic Data") +
    graph_formatting

ggsave(
    filename = "mortage_rates.png",
    plot = mortgage_rate_graph,
    device = "png"
)


comb_start_graph = long_comb %>% 
    ggplot(aes(x = date,  y = value)) +
    geom_line(aes(color = name))


ggsave(
    filename = "combined_starts.png",
    plot = comb_start_graph,
    device = "png"
)
```